package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at May 22, 2007 1:07:29 AM

import net.xytra.wobmail.export.ExportVisitable;

import com.webobjects.appserver.WOContext;

public class FileViewPage extends ExportVisitable
{
	public FileViewPage(WOContext context)
	{
		super(context);
	}

	protected String filenameDesignator()
	{
		return ("filename=");
	}

}
