package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at Apr 23, 2007 12:18:37 AM

import net.xytra.wobmail.export.ExportVisitable;

import com.webobjects.appserver.WOContext;

public class FileDownloadPage extends ExportVisitable
{
	public FileDownloadPage(WOContext context)
	{
		super(context);
	}

	protected String filenameDesignator()
	{
		return ("attachment; filename=");
	}

}
