package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 7:24:59 PM

import net.xytra.wobmail.application.Session;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import er.extensions.ERXNonSynchronizingComponent;

public class XWMPageWrapper extends ERXNonSynchronizingComponent
{
	public XWMPageWrapper(WOContext context) {
		super(context);
	}

	public WOComponent composeAction()
	{
		return (pageWithName(XWMCompose.class.getName()));
	}

	public WOComponent inboxAction()
	{
		((Session)session()).resetAvailableInboxMessages();
		return (pageWithName(XWMList.class.getName()));
	}

	/**
	 * Get the page title of the current page.
	 * This component supports two bindings: pageTitle can specify the
	 * pageTitle to be displayed as is.  If unspecified, try to translate the
	 * string for binding pageTitleKey.  If a page title can be determined,
	 * return "Wobmail :: (page title)", otherwise just "Wobmail".
	 *
	 * @return title of web page, usually "Wobmail :: (something)".
	 */
	public String pageTitle()
	{
		// First, we try to get the page title as directly specified:
		String pageTitle = stringValueForBinding("pageTitle");

		// If that wasn't specified, get key and localize
		if (pageTitle == null) {
			String pageTitleKey = stringValueForBinding("pageTitleKey");
	
			// TODO: Localization should occur here
			pageTitle = pageTitleKey;
		}

		return ("Wobmail" + (pageTitle != null ? " :: " + pageTitle : ""));
	}

}
