package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at Apr 22, 2007 1:55:05 AM

import java.io.IOException;

import javax.mail.BodyPart;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Part;

import com.webobjects.appserver.WOContext;

import er.extensions.components.ERXNonSynchronizingComponent;

public class XWMMultipartContent extends ERXNonSynchronizingComponent
{
	public int currentPartIndex;

	private Multipart _multipart;

	public XWMMultipartContent(WOContext context)
	{
		super(context);
	}

	public BodyPart currentPart() throws IOException, MessagingException
	{
		return (multipart().getBodyPart(currentPartIndex));
	}

	public int partsCount() throws MessagingException, IOException
	{
		return (multipart().getCount());
	}

	protected Multipart multipart() throws IOException, MessagingException
	{
		if (_multipart == null)
			_multipart = (Multipart)((Part)objectValueForBinding("part")).getContent();

		return (_multipart);
	}

	public String partInfo() throws IOException, MessagingException
	{
		return (multipart().getContentType().split(";")[0]);
	}

}
