package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 7:24:59 PM

import com.webobjects.appserver.WOContext;

public class XWMPageWrapper extends XWMAbstractPage
{
	private static final String PAGE_WRAPPER_PAGE_NAME = "XWMPageWrapper";

	public XWMPageWrapper(WOContext context) {
		super(context);
	}

	/**
	 * Get the page title of the current page.
	 * This component supports two bindings: pageTitle can specify the
	 * pageTitle to be displayed as is.  If unspecified, try to translate the
	 * string for binding pageTitleKey.  If a page title can be determined,
	 * return "Wobmail :: (page title)", otherwise just "Wobmail".
	 *
	 * @return title of web page, usually "Wobmail :: (something)".
	 */
	public String pageTitle()
	{
		// First, we try to get the page title as directly specified:
		String pageTitle = stringValueForBinding("pageTitle");

		// If that wasn't specified, get key and localize
		if (pageTitle == null) {
			// Get page title key for localizer
			String pageTitleKey = PAGE_WRAPPER_PAGE_NAME + '.' + stringValueForBinding("pageTitleKey");

			pageTitle = localizer().localizedStringForKeyWithDefault(pageTitleKey);
		}

		return ("Wobmail" + (pageTitle != null ? " :: " + pageTitle : ""));
	}

}
