package net.xytra.wobmail.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 7:24:59 PM

import net.xytra.wobmail.application.Session;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

import er.extensions.ERXNonSynchronizingComponent;

public class XWMPageWrapper extends ERXNonSynchronizingComponent
{
	public XWMPageWrapper(WOContext context) {
		super(context);
	}

	public WOComponent composeAction()
	{
		return (pageWithName(XWMCompose.class.getName()));
	}

	public WOComponent inboxAction()
	{
		((Session)session()).resetAvailableInboxMessages();
		return (pageWithName(XWMList.class.getName()));
	}

}
